on: ["push", "pull_request"]

name: Test

jobs:
  functional:
    runs-on: ubuntu-latest
    steps:
    - name: Cache compiler installations
      uses: actions/cache@v2
      with:
        path: |
          /home/runner/work/_temp/_github_home/.solcx
          /home/runner/work/_temp/_github_home/.vvm/vyper-*
        key: ${{ runner.os }}-compiler-cache

    - name: Cache build installations
      uses: actions/cache@v2
      with:
        path: |
          ./.build
        key: ${{ runner.os }}-build-cache

    - uses: actions/checkout@v2
    - uses: ApeWorX/github-action@main
